<?php
return [
        //header and footer modals
    'our-modal-header' => 'Nuestro Concepto',
    'our-modal-footer' => 'Más de 20 años formando hombres de bien',
    //information contents body modals
    'our-content-1' => 'La sociedad en general, como entorno de la universidad, y la universidad misma, han estado sometidas durante las últimas tres décadas, a cambios de gran trascendencia: demográficos, económicos, sociales, políticos y tecnológicos, cambios que indudablemente han repercutido en las formas de dirección, organización y gestión de estas instituciones. Los modelos de organización y gestión tradicionales fueron concebidos para dar respuestas a entornos mucho más sencillos y estables, y hoy día son poco eficaces y operativos.',
    'our-content-2' => ' Se hizo necesario, entonces, que las universidades se acogiesen a modelos organizacionales que les permitieran ser parte funcional y participativa de su entorno, respondiendo así a una realidad dinámica y cambiante y por lo tanto con un alto grado de incertidumbre. ',
    'our-content-3' => 'La Universidad de Margarita, es una institución joven, creada a fines del año 1999, y nace bajo una concepción organizacional que la caracteriza como un sistema social abierto, dinámico y flexible, funcionalmente vinculado a un sistema más amplio (la sociedad), que constituye su entorno, dispuesto al cambio, y articulado internamente mediante subsistemas integrados funcionalmente, con interacciones específicas entre sus participantes. ',
    'our-content-4' => 'La Universidad de Margarita ha adoptado como su esquema gerencial básico, el modelo sistémico. La noción fundamental de un sistema consiste simplemente en que es una serie de partes interrelacionadas que trabajan sinérgicamente. En este concepto se haya implícito un grado de totalidad que convierte al todo en algo diferente a las partes individuales consideradas por separado y algo más que ellas. El concepto de sistema es primordialmente un modo de pensar acerca de la labor gerencial. Provee un esquema para la visión de factores internos y externos de la institución, en la forma de un todo integrado. El fin principal de la adopción de este modelo sistémico y de una dirección estratégica de la institución, es el logro del incremento de su capacidad de respuesta a la demanda social, con características de calidad, pertinencia, eficacia y eficiencia.',
];